# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20170108_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='지원자', to=settings.AUTH_USER_MODEL),
        ),
    ]
