# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_auto_20170108_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='upload_user',
            field=models.CharField(default='아무개', max_length=30),
        ),
    ]
