# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import resumes.models
import resumes.storage


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_auto_20170108_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='document',
            field=models.FileField(storage=resumes.storage.OverwriteStorage(), upload_to=resumes.models.change_file_name),
        ),
    ]
