# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_auto_20170109_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='upload_user_real_name',
            field=models.CharField(default='홍길동', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='upload_user',
            field=models.CharField(default='xxxx', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='upload_user_student_number',
            field=models.IntegerField(default='2015123456'),
        ),
    ]
