# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_auto_20170109_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='upload_user_student_number',
            field=models.IntegerField(default=20151234567),
        ),
    ]
