# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('grade', models.CharField(choices=[('FR', '1학년'), ('SO', '2학년'), ('JR', '3학년'), ('SR', '4학년')], default='one', max_length=2)),
                ('register', models.BooleanField(default=True)),
                ('majoring', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
