# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register',
            field=models.CharField(choices=[('FR', '1학년'), ('SO', '2학년'), ('JR', '3학년'), ('SR', '4학년')], default='Y', max_length=2),
        ),
    ]
