# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170109_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register',
            field=models.CharField(choices=[('Y', '재학생'), ('N', '휴학생')], default='Y', max_length=2),
        ),
    ]
