# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170109_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default='01012345678'),
        ),
    ]
