# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170109_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_number',
            field=models.IntegerField(default='2015123456'),
        ),
    ]
